package com.test.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-11-27T15:19:20.741+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://cxf.apache.hello.outofmemory.cn/", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloService {

    @WebMethod
    @RequestWrapper(localName = "hello", targetNamespace = "http://cxf.apache.hello.outofmemory.cn/", className = "com.test.cxf.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://cxf.apache.hello.outofmemory.cn/", className = "com.test.cxf.HelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
