package com.fzservice.entity;
// default package
// Generated 2012-9-23 17:28:23 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Tbtest generated by hbm2java
 */
@Entity
@Table(name = "tbtest", catalog = "test")
@GenericGenerator(name = "uuidPk", strategy = "uuid")
public class Tbtest implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4504062225811874818L;
	private String id;
	private String name;

	public Tbtest() {
	}

	public Tbtest(String id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id
	@GeneratedValue(generator = "uuidPk")
	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
