
DROP TABLE IF EXISTS `cc_dictionary`;
CREATE TABLE `cc_dictionary` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL COMMENT '名称',
  `order` INT(11) DEFAULT NULL COMMENT '排序',
  `type` INT(11) DEFAULT NULL COMMENT '类型 例如：流程节点',
  `description` VARCHAR(200) DEFAULT NULL COMMENT '描述',
  `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '5.6.5+有效',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='字典';


DROP TABLE IF EXISTS `cc_user_flow_state`;
CREATE TABLE `cc_user_flow_state` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL COMMENT '用户id',
  `flow_id` INT(11) DEFAULT NULL COMMENT '流程节点id',
  `flow_status` INT(11) DEFAULT NULL COMMENT '流程节点状态',
  `handle_state` INT(11) DEFAULT NULL COMMENT '客服处理状态 0-未处理 1-处理中 2-已回访',
  `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '5.6.5+有效',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='用户流程状态';


DROP TABLE IF EXISTS `cc_user_flow_count`;
CREATE TABLE `cc_user_flow_count` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `flow_id` INT(11) DEFAULT NULL COMMENT '流程节点id',
  `flow_status` INT(11) DEFAULT NULL COMMENT '流程节点状态',
  `user_count` INT(11) DEFAULT NULL COMMENT '人数',
  `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '5.6.5+有效',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='用户流程状态统计';


DROP TABLE IF EXISTS `cc_work_sheet`;
CREATE TABLE `cc_work_sheet` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `state_id` INT(11) NOT NULL COMMENT '用户流程状态记录id',
  `user_backend_id` INT(11) NOT NULL COMMENT '后台工作人员id',
  `description` VARCHAR(400) DEFAULT NULL COMMENT '描述',
  `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '5.6.5+有效',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='工作记录表';







