package com.we.backend.track.dao;


import com.we.backend.track.domain.dto.ResourceMenuDto;
import com.we.backend.track.domain.vo.Resource;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * 菜单资源DAO
 *
 *
 */
@Mapper
public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_resource
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    int deleteByPrimaryKey(Integer resId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_resource
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_resource
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    void insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_resource
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    Resource selectByPrimaryKey(Integer resId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_resource
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_resource
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    int updateByPrimaryKey(Resource record);


    /**
     * 资源信息COUNT
     * @param resource 资源实体
     * @return
     */
    Long selectCountResource(Resource resource);
    /**
     * 资源信息分页列表显示
     * @param resource 资源实体
     * @return
     */
    List<Resource> selectResourceListByPage(Resource resource);

    /**
     * 查询资源父级菜单
     * @return
     */
    List<ResourceMenuDto>selectParentIdResList();

    List<Resource> selectResLevelListByParentid(@Param("resParentid") Integer resParentid);


    
}