package com.we.backend.track.dao;

import com.we.backend.track.domain.vo.RoleResource;
import org.apache.ibatis.annotations.Mapper;


/**
 * 角色资源关联DAO
 *
 * @author YK
 * @date 2017 7/24
 */
@Mapper
public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_role_resource
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    int deleteByPrimaryKey(Integer roleResId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_role_resource
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_role_resource
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    int insertSelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_role_resource
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    RoleResource selectByPrimaryKey(Integer roleResId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_role_resource
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    int updateByPrimaryKeySelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_role_resource
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    int updateByPrimaryKey(RoleResource record);
}